name: CI

on:
  pull_request:
    branches:
    - '*'
  push:
    branches:
    - main

defaults:
  run:
    shell: bash

jobs:
  all:
    name: All

    strategy:
      matrix:
        target:
        - x86_64-pc-windows-msvc
        - i686-pc-windows-msvc
        include:
        - target: x86_64-pc-windows-msvc
          os: windows-2019
        - target: i686-pc-windows-msvc
          os: windows-2019

    runs-on: ${{matrix.os}}

    env:
      RUSTFLAGS: --deny warnings

    steps:
    - uses: actions/checkout@v2

    - name: Install Rust Toolchain Components
      uses: actions-rs/toolchain@v1
      with:
        components: clippy, rustfmt
        override: true
        target: ${{ matrix.target }}
        toolchain: stable

    - uses: Swatinem/rust-cache@v1

    - name: Check Lockfile
      run: |
        cargo update --locked --package windows-switcher

    - name: Test
      uses: actions-rs/cargo@v1
      with:
        use-cross: ${{ matrix.use-cross }}
        command: test
        args: --all --target=${{ matrix.target }}

    - name: Clippy
      run: cargo clippy --all --all-targets

    - name: Format
      run: cargo fmt --all -- --check